"""mxr drink table.

Revision ID: 11ca08befee1
Revises:
Create Date: 2025-02-07 19:20:57.792409

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "11ca08befee1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drinks",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("garnish", sa.String(), nullable=True),
        sa.Column("ingredients", sa.String(), nullable=False),
        sa.Column("preparation", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="mxr",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drinks", schema="mxr")
    # ### end Alembic commands ###
