name: pypi publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: pypi publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "2.0.1"


      - name: Build and publish
        run: |
          poetry build
          poetry publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
